Step3
Loly-webdev/blog pull request #34
Opened 2020-06-13 16:22 UTC by Loly-webdev

Step 3 : page d'accueil et administration #29

 Nom + Prénom
 Photo et/ou logo
 phrase d'accroche
 Menu de navigation
 Formulaire de contact fonctionnel
 Lien vers le CV en PDF
 Liens vers les réseaux sociaux
 Ajout d'un lien conduisant à l'administration dans le footer
 Espace administration accessible uniquement aux utilisateurs inscrits et validés.

2020-07-08 15:02 UTC, fmoy requested changes

2020-07-08 15:02 UTC, fmoy commented on core/DefaultAbstract/AdminAbstractController.php
> +        if ('admin' === isset($_SESSION['role'])) {
faux => [voir doc](https://www.php.net/manual/fr/function.isset.php)

2020-07-08 15:02 UTC, fmoy commented on core/DefaultAbstract/DefaultAbstractController.php
> +        assert($user instanceof User);
inutile

2020-07-08 15:02 UTC, fmoy commented on core/DefaultAbstract/DefaultAbstractController.php
> +        $user = (new UserRepository())->findOneById($userId);
`return (new UserRepository())->findOneById($userId);`

2020-07-08 15:02 UTC, fmoy commented on core/Provider/ConfigurationProvider.php
> +        return static::$config['myMail'];
`return static::$config['myMail'] ?? '';`

2020-07-08 15:02 UTC, fmoy commented on core/Provider/ConfigurationProvider.php
>          return static::$config['salt'];
techniquement si la clef n'existe pas ça génère une erreur

2020-07-08 15:02 UTC, fmoy commented on core/Provider/TwigProvider.php
> +
saut de ligne inutile

2020-07-08 15:02 UTC, fmoy commented on core/Traits/Controller/AddControllerTrait.php
> +        if (isset($formSubmitted)) {
on utilise pas le `$form->isSubmited() ?`

2020-07-08 15:02 UTC, fmoy commented on core/Traits/Controller/CUDControllerTrait.php
> +                'Une erreur est survenue.');
indentation

2020-07-08 15:02 UTC, fmoy commented on public/js/script.js
> +/* ANIMATION TITLE */
étrange ce fichier on comprends pas à quoi il sert script.js c est vague et on versionne le dossier public ?

2020-07-08 15:02 UTC, fmoy commented on src/Controller/Admin/UserAdminController.php
> +        assert($user instanceof User);
techniquement si $user est null tu as un soucis ...

2020-07-08 15:02 UTC, fmoy commented on src/Controller/AuthenticationController.php
> +
saut de ligne inutile

2020-07-08 15:02 UTC, fmoy commented on src/Controller/ContactController.php
> +                'user' => $user ?? new User,
`'user' => $user ?? new User();`

2020-07-08 15:02 UTC, fmoy commented on src/Controller/RegisterController.php
>              return $role = (new User())::ROLE_ADMIN;
Du gros n'importe quoi :) tu veux pas utiliser $this à la place de new user() ? et retirer les variables $role inutiles;

2020-07-08 15:02 UTC, fmoy commented on src/Controller/RegisterController.php
> +            $this->check($email, $password, $password2);
tu peux simplifer
`
$formValues = $formValidator->getFormValues();
$this->check(
     $formValues['mail'] ?? '',
     $formValues['password'] ?? '',
     $formValues['password2'] ?? ''
);
`
Fait attention si jamais tu as rien à comparer tache de faire en sorte que cela ne te retourne pas Ok

2020-07-08 15:02 UTC, fmoy commented on src/Controller/RegisterController.php
> +        $role = $this->role();
C'est pas logique du tout ces 2 lignes à la suite.

2020-07-08 15:02 UTC, fmoy commented on src/Controller/RegisterController.php
> +        if ($password !== $password2) {
Et si les deux password sont vide ?

2020-07-08 15:02 UTC, fmoy commented on src/Controller/RegisterController.php
> +        (new User())->setMail($email)
mais what ??? pourquoi tu fais un new user() tu créer un compte vide à chaque fois alors utilise $this !!!

2020-07-08 15:02 UTC, fmoy commented on src/Entity/Article.php
>      public function setTitle($title)
a voir si ça vaut le coup de faire du typage en entrée et sortie de méthode

2020-07-08 15:02 UTC, fmoy commented on src/Entity/User.php
> +        return self::ROLE_ADMIN === $this->getRole();
static pas de self
ps ->  tu vois bien qu'ici tu fais pas de `(new user())->getRole();` alors fait gaffes

2020-07-08 15:02 UTC, fmoy commented on src/Entity/User.php
>          if (in_array($role, self::ROLES)) {
static

2020-07-08 15:02 UTC, fmoy commented on src/Entity/User.php
>          return $this->role = $role;
logique zéro. Revois ton fonctionnement, et concerve le chainage de méthode sinon n'en fait pas.

2020-07-08 15:02 UTC, fmoy commented on src/Entity/User.php
>          return isset(self::ROLES[$code])
du coup ...
`return self::ROLES[$code] ?? 'Aucun role définit';`

2020-07-08 15:02 UTC, fmoy commented on src/Service/Email.php
> +        if (mail($myMail, $subject, $message, $header)) {
if ( true === true) return true else return false ...
super logique 
`return mail($myMail, $subject, $message, $header);`
Si jamais mail te retourne pas un boolean tu precises le test simplement

2020-07-08 15:02 UTC, fmoy commented on src/Service/Message.php
> +}
saut  de ligne ton ide est pas configuré ?

2020-07-08 15:02 UTC, fmoy commented on src/utils/Helper.php
> +        $text = nl2br($text);
return directement

2020-07-08 15:02 UTC, fmoy commented on template/back/article/editArticle.html.twig
> +                    <div class="col-md-12">
inutile le md-12

2020-07-08 16:11 UTC, Loly-webdev commented on core/Provider/ConfigurationProvider.php
>          return static::$config['salt'];
???

2020-07-08 16:11 UTC, Loly-webdev commented on core/Traits/Controller/AddControllerTrait.php
> +        if (isset($formSubmitted)) {
???

2020-07-08 16:11 UTC, Loly-webdev commented on public/js/script.js
> +/* ANIMATION TITLE */
c'est l'animation du sous titre de l'accueil.

2020-07-08 16:11 UTC, Loly-webdev commented on src/Controller/Admin/UserAdminController.php
> +        assert($user instanceof User);
???

2020-07-08 16:12 UTC, Loly-webdev commented on core/DefaultAbstract/AdminAbstractController.php
> +        if ('admin' === isset($_SESSION['role'])) {
corrigé

2020-07-09 16:02 UTC, Loly-webdev commented on src/Controller/RegisterController.php
> +        if ($password !== $password2) {
les champs sont requis ça ne peut pas être vide normalement.

2020-07-09 16:02 UTC, Loly-webdev commented on src/Controller/RegisterController.php
> +        (new User())->setMail($email)
???

2020-07-15 13:44 UTC, fmoy approved these changes

2020-07-15 13:45 UTC, merged